Added a popup window
NalianAchei2020/Portfolio pull request #12
Opened 2023-06-21 14:09 UTC by NalianAchei2020

# 📝 Accomplishment
- Added a popup window
- Integrated javascript

2023-06-21 14:53 UTC, emmanuellekamwa requested changes
**STATUS: INVALID ❌🛑**
Hello @NalianAchei2020 and @hetrox8 👋
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has failing linters and the commit history shows that only one person contributed to the project. Please kindly fix the linters and ensure that everybody contributes to the project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-21 15:15 UTC, NalianAchei2020 commented
> **STATUS: INVALID ❌🛑** Hello @NalianAchei2020 and @hetrox8 👋 While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that has failing linters and the commit history shows that only one person contributed to the project. Please kindly fix the linters and ensure that everybody contributes to the project.
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-21 15:25 UTC, NalianAchei2020 commented
Hi @emmanuellekamwa 
I think you did not check the commit history very well. I did this project with my coding partner Okari as seen in this screenshot
![image](https://github.com/NalianAchei2020/Portfolio/assets/88759996/f3655d8c-9075-4771-bbca-7aa7766748cd)
And for the liners, it fails at webhint which is a normal error that occurs. Most of the code reviewers said it is normal to submit with error.  Please can you help me in resolving the error? My past projects were approved with the failing webhint linters

2023-06-21 15:31 UTC, emmanuellekamwa commented
For the contribution your partner is supposed to have as many commits as you but here he has only one commit. In this case een another reviewer would have invalidated it.

2023-06-21 15:54 UTC, LionRouge1 reviewed
Hi **team**, 

![done](https://media.giphy.com/media/gnE4FFhtFoLKM/giphy.gif)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have JavaScript linter set up. Since you are using JavaScript in this project, kindly make sure you set up both [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) linters.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-21 20:05 UTC, AdnanOlarmmi requested changes
Hi @NalianAchei2020 and @hetrox8, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Nice UI design.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-21 20:05 UTC, AdnanOlarmmi commented on style.css
- [ ] According to the requirement, the app is meant to have a popup on click of the `See Project` button, but what it does is replace the card with the popup interface, Please 😃 this is not the expected functionality, kindly check out [this repo](https://adnanolarmmi.github.io/Demo-Portfolio/) for the correct explanation.

![image](https://github.com/NalianAchei2020/Portfolio/assets/41163571/70d0051b-94d6-4b1d-93b3-b602e5c56315)

2023-06-21 20:05 UTC, AdnanOlarmmi commented on style.css
> +
- [x] Kindly fix the spacing to the right of the popup window to match the design 💯, part of a good design is that diagonal spacings are equal.

- Your design
<img width="894" alt="image" src="https://github.com/NalianAchei2020/Portfolio/assets/41163571/16d260f5-b1fa-4980-b187-dd48ede602b8">

- Figma design
<img width="317" alt="image" src="https://github.com/NalianAchei2020/Portfolio/assets/41163571/3891b8d5-873c-4ab1-a5f8-1d766eaf838b">

2023-06-21 20:05 UTC, AdnanOlarmmi commented on style.css
> +  }
- [ ] Kindly fix the image resolution, you can do this by using CSS transform: scale to enlarge the image, of working on the aspect ratio of the image, or putting the image in a container and then making the image width and height a 100% of the container, then making the object-fit as cover and enlarge the container instead of the image, or any other method you deem fit, there's no one way of doing things in the programming world 😊.

2023-06-21 20:05 UTC, AdnanOlarmmi commented on style.css
> +  }
- [ ] Kindly ensure to add the **blurry** modal background to your popup window likewise to match the design 💯 🤗

<img width="317" alt="image" src="https://github.com/NalianAchei2020/Portfolio/assets/41163571/3eecde11-f670-42b9-9106-90657dfce04f">

2023-06-21 20:05 UTC, AdnanOlarmmi commented on style.css
> +  }
- [ ] Kindly set the languages container to align with the horizontal plane of the button to match the design 💯 as you'll soon be doing in your next job.

- Your design
<img width="350" alt="image" src="https://github.com/NalianAchei2020/Portfolio/assets/41163571/f786b60a-45a8-495f-b0e3-ab2b08985f6b">

- Figma design
<img width="139" alt="image" src="https://github.com/NalianAchei2020/Portfolio/assets/41163571/dea7860d-1a78-4cc9-b996-dfe222395400">


- Kindly fix the `see-source` and remove the hyphen so it becomes `See Source` just like the design, attention to detail is very important as a developer.
- Kindly use the exact icon as the Figma design, since you can download/export it from Figma UI by the right.
- Kindly align the See live or See Source text centered to their respective icons.

2023-06-23 02:20 UTC, franclobo approved these changes
Hi @NalianAchei2020, 

# STATUS: APPROVED 😃 

![git-merge](https://github.com/NalianAchei2020/Portfolio/assets/58642949/27dce3eb-4937-4eb3-9336-0124e51194ab)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Good UI ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-24 06:33 UTC, merged