Added  work  and about me sections
NalianAchei2020/Portfolio pull request #3
Opened 2023-06-02 17:19 UTC by NalianAchei2020

# 📝 Accomplishments
*  Added work section to display past and recent project
*  Added about self section.
*  Update the readme file

2023-06-02 19:57 UTC, Bantealem requested changes
Hi @NalianAchei2020 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/0bfUJGAlN5HQhFZkWR/giphy.gif" style ="height:50px"/>

## Highlights
- [x] No Linters error
- [x] Correct GitHub flow
- [x] Descriptive PR summary and title
- [x] Professional README

## Required Changes ♻️
- [ ] It would be better to not fix the header of the page since it makes the user interface somehow not good. Look at the top corner of the page.
![Screenshot from 2023-06-02 22-18-50](https://github.com/NalianAchei2020/Portfolio/assets/101523582/14adfa16-a4db-4389-999c-2fba993f8aea)
- [ ] Please make sure your design is the same as the Figma temlate
Your design
![Screenshot from 2023-06-02 22-37-55](https://github.com/NalianAchei2020/Portfolio/assets/101523582/b772624c-d03f-4409-b787-b0e747621801)

The Figma design
![Screenshot from 2023-06-02 22-39-26](https://github.com/NalianAchei2020/Portfolio/assets/101523582/714b9ab8-3a61-475a-9f0c-0e2751eccd6e)

Your design
![Screenshot from 2023-06-02 22-47-39](https://github.com/NalianAchei2020/Portfolio/assets/101523582/3d4e1d8b-3628-48f0-b922-2b715d7ae265)

Figma design
![Screenshot from 2023-06-02 22-48-42](https://github.com/NalianAchei2020/Portfolio/assets/101523582/22ff721c-9edb-4439-9dcd-c101480896a8)
- [ ] Please make sure you used `Poppins` font family for your text. Since it's based on the Figma design.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 19:57 UTC, Bantealem commented on style.css
> +}
Good job so far. Kindly add the `.btn-project: hover` property for your button. It will create visual feedback for the user. Please fix it.

2023-06-02 19:57 UTC, Bantealem commented on index.html
> +                        <li><a href="#"><img src="Images/Vector1.png"/></a></li>
Great job. Please make sure your social media link is redirecting to your profile. For example, when I click on the Twitter icon it should redirect me to your Twitter profile. just replace `#` with your account link. So people can easily contact you via this social media. Kindly fix it.

2023-06-02 21:47 UTC, NalianAchei2020 commented on style.css
> +}
Hi @Bantealem 
Can I  add the .btn-project: hover property for the button to any color?  
I don't know the one specify in the design.  I have been stuck on this for a while

2023-06-02 21:51 UTC, NalianAchei2020 commented on index.html
> +                        <li><a href="#"><img src="Images/Vector1.png"/></a></li>
Hi @Bantealem 
What of the icons that  I have not signed up on, can I redirect them to any link?

2023-06-02 22:08 UTC, NalianAchei2020 commented
Hi @Bantealem 
I am already using the Poppins font family in my project.
![image](https://github.com/NalianAchei2020/Portfolio/assets/88759996/26823478-02e9-4a64-b8ee-a30febd4f48d)
Please if this is not the right way to do it. Please help me with the right format

2023-06-03 05:48 UTC, Bantealem commented on index.html
> +                        <li><a href="#"><img src="Images/Vector1.png"/></a></li>
Signup for each account and add the link here @NalianAchei2020

2023-06-03 05:49 UTC, Bantealem commented on style.css
> +}
Yeah, you can add. @NalianAchei2020

2023-06-03 05:51 UTC, Bantealem commented
Great if you already used it. so implement changes for the other task and asked for a review again @NalianAchei2020.

2023-06-03 07:28 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @NalianAchei2020 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🌟

- ✔️Understand how to parse a Figma design to create a UI.
- ✔️ Use Flexbox to place elements on the page.
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 07:28 UTC, abdulhamiid commented on index.html
> +                </div>
[OPTIONAL] - This requirement is marked optional but highly recommended, according to the project requirements, please use `ul` and `li` for categories in "About myself" section. Languages, Frameworks, and Skills should be list items.



```HTML
<ul>
  <li>
    <h3>Languages</h3>
    . . . 
    <ul>
       <li class="skill"><img src="Images/javascript.png"><span>Javascript</span></li>
       <li> . . .  </li>
       <li> . . .  </li>
    </ul>
  </li>
  <li>
    <h3>Frameworks</h3>
     . . . 
  </li>
  <li> 
   <h3>Frameworks</h3>
    . . . 
  </li>
</ul>
```

2023-06-03 07:28 UTC, abdulhamiid commented on index.html
> +                    <h3>Skills</h3>
As suggested by the previous reviewer, as you have updated the font for `Languages` kindly use the `Poppins` font family for the `Frameworks` and `Skills` also. 🤗🛠

Your design
![image](https://github.com/NalianAchei2020/Portfolio/assets/78251927/a98a72b3-185b-4d42-b18f-9b03c127e83e)

2023-06-03 07:28 UTC, abdulhamiid commented on index.html
> +                      <button type="button" class="btn-project">Get my resume</button>
[OPTIONAL] It would be nice if we follow the button styling: `Active`, `Hover` and `Pressed` (see design)

![image](https://github.com/NalianAchei2020/Portfolio/assets/78251927/79f6bcf9-b34e-4086-9d9f-18529f01ce8c)

2023-06-03 07:28 UTC, abdulhamiid commented on index.html
> +                        <button type="button" class="btn-project">See Project</button>
[OPTIONAL] - For the buttons ("See project") 

It would be nice if we follow the button styling: `Active`, `Hover`, and `Pressed`  🤗👍

2023-06-03 09:34 UTC, NalianAchei2020 commented on index.html
> +                    <h3>Skills</h3>
Please I need help here, I have added the font family and nothing is changing
Please can you help me?

2023-06-03 10:57 UTC, NalianAchei2020 commented on index.html
> +                    <h3>Skills</h3>
Hi @abdulhamiid 
Please I need help here, I have added the font family and nothing is changing
Please can you help me?

2023-06-03 13:46 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @NalianAchei2020 , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Well done implementing the requestes changes.  🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 13:52 UTC, merged