Added Desktop View
NalianAchei2020/Portfolio pull request #8
Opened 2023-06-08 22:22 UTC by NalianAchei2020

# 📝 Accomplishments
- Added desktop view

2023-06-08 23:31 UTC, shahadat3669 requested changes
Hi @NalianAchei2020 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
Correct use of GitHub Flow ✅
Well-structured files ✅
All linter checks are passing ✅
Descriptive PR title ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## ⚠️ WARNING ⚠️
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 23:31 UTC, shahadat3669 commented on style.css
Great Responsive version! However, upon reviewing your project, I noticed that all sections have a mismatched right margin in the mobile version. This seems to be caused by the 2.5rem margin in the sections with the class name "card". 

- [ ] Please consider updating this margin to resolve the issue. 🙏 

- [ ] [Optional] Additionally, I would recommend using the `<article>` tag instead of the `<section>` tag to represent a card. The `<article>` tag is more semantically meaningful in this context. You can refer to [this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Elem0ent/article) to learn more about it.
![image](https://github.com/NalianAchei2020/Portfolio/assets/55840999/1d224232-bda9-4265-9c7b-778a33695f7e)
- [ ] In the desktop version, your design looks good. However, I noticed that there is a break in the layout around the viewport width of `1050px` to `1070px`. Please make the necessary updates to ensure that your UI remains consistent and visually appealing within this range. 🙏 
![image](https://github.com/NalianAchei2020/Portfolio/assets/55840999/a4115ed3-5abe-4f67-b6e1-520798618128)


Please make the necessary changes accordingly. 🙏  Keep up the good work! 👍

2023-06-09 04:24 UTC, NalianAchei2020 commented on style.css
Hi @shahadat3669 
Please can I give you a call on Zoom so you could help me?

2023-06-10 09:11 UTC, Bantealem reviewed
Hi @NalianAchei2020 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has missed the previous reviewer's inline comments so I can't give you a review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-10 11:00 UTC, Bantealem requested changes
Hi @NalianAchei2020 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Professional README
- [x] Correct Github flow
- [x] Descriptive PR summary
## Required Changes ♻️
# Warning 
- [ ] Please don't delete the inline comments given by the previous reviewer. It won't be acceptable to delete the inline comments.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 11:00 UTC, Bantealem commented on style.css
> +  }
Please make sure your design is the same as the Figma design. Currently, the background image position is not the same as the Figma one. Kindly fix it.

Your design
![image](https://github.com/NalianAchei2020/Portfolio/assets/101523582/22794ed0-9a35-4d98-8dc8-94f4fafe36cb)

Figma design
![image](https://github.com/NalianAchei2020/Portfolio/assets/101523582/a81d2209-66b6-4181-9090-23636844ace1)
 - [ ] Please make sure to decrease the size of social media icons too since it is greater than the one in the Figma.

2023-06-10 11:00 UTC, Bantealem commented on style.css
> +  }
Great job. Please make sure the `li` on your page is displayed. Currently, I can't see the `li` in your portfolio.  Kindly, fix the `margin` of the `li`.

Your design
![image](https://github.com/NalianAchei2020/Portfolio/assets/101523582/22ffc1e0-4158-440d-bafa-1758be600680)

Figma design
![image](https://github.com/NalianAchei2020/Portfolio/assets/101523582/b38f8307-b05d-4fd5-a5d3-97274eb12bfa)

2023-06-10 11:00 UTC, Bantealem commented on style.css
> +  }
Great job. Please make sure the `li` on your page is displayed. Currently, I can't see the `li` in your portfolio.  Kindly, fix the `margin` of the `li`

Your design
![image](https://github.com/NalianAchei2020/Portfolio/assets/101523582/a57bd667-a1ba-423e-999e-6fd6c632189f)

Figma design
![image](https://github.com/NalianAchei2020/Portfolio/assets/101523582/4d19e376-6e94-4dc2-a481-51b495ebe91a)

- [ ] Kindly decrease the `font size` for the title.

Your design 
![image](https://github.com/NalianAchei2020/Portfolio/assets/101523582/77f5af96-ebdf-41ef-ab4b-b463ee4cf9a3)
 
Figma design
![image](https://github.com/NalianAchei2020/Portfolio/assets/101523582/c84356fb-3184-43ee-a6c7-52a217bac9d7)
Your design
![image](https://github.com/NalianAchei2020/Portfolio/assets/101523582/f2f2fdcd-52b6-4de7-a29c-d4d748b9f984)

Figma design
![image](https://github.com/NalianAchei2020/Portfolio/assets/101523582/fc56f9c7-49c3-4151-a9c7-a0bfa83c743f)

2023-06-10 11:00 UTC, Bantealem commented on style.css
> +    max-width: 100%;
Please make sure the background image position is the same as the Figma design. Kindly, fix it
Your design
![image](https://github.com/NalianAchei2020/Portfolio/assets/101523582/b9532e93-f973-46ff-b165-6dea4d3ba144)

Figma design
![image](https://github.com/NalianAchei2020/Portfolio/assets/101523582/6fc425a5-d276-4f54-b55f-b22569e14df3)

2023-06-10 19:01 UTC, Johnadibe approved these changes
# Status: Approved ✔️
### Hi @NalianAchei2020👋🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![LeonardoInGatsby](https://user-images.githubusercontent.com/38088818/233992044-ad00b20f-3f2f-4c86-8b94-1e613432af5f.gif)

## Highlights
- Implemented all changes requested by the previous code reviewer✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 19:01 UTC, Johnadibe commented on index.html
>                  <li><a href="https://twitter.com/home"><img src="./Images/TWIT.PNG.jpg"></a></li>
> [OPTIONAL] As this was not pointed out by the previous code reviewer, Kindly ensure you align the About section to match with the Figma design. This will ensure consistency and improves your attention to detail.👍
> 
> Figma design:
> 
> ![at1](https://github.com/NalianAchei2020/Portfolio/assets/40009354/7de9371e-9f8e-4168-be05-1745aac01012)
> 
> Your design:
> 
> ![at](https://github.com/NalianAchei2020/Portfolio/assets/40009354/9afe0e9e-efa0-47f2-8a7a-2318bb069659)
>

2023-06-10 20:09 UTC, merged